"BUILDING" = "#fff100"
"INT_SPACE" = "#ff8c00"
"ENV_FEATURES" = "#ec008c"
"REGION" = "#00b294"
"SPACIAL" = "#00bcf2"
"COUNTRY"= "#bad80a"
"CONTINENT" = "#e6e6fa"
"POPULATED_PLACE" = "#fa8072"
"NPIP" = "#f5f5dc"
"DISCUSS" = "#66cdaa"
"DLF" = "#f0f8ff"
"ENVIRONMENTAL_FEATURE" = "#fbbaf7"
"SPATIAL_OBJ" = "#fbab0a"
"DISTINCT_LANDSCAPE_FEATURE" = "#5b94de"
"RIVER" = "#fbab0a"